# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 09:35
from __future__ import unicode_literals

import dateutil.utils
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appezzamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='nome appezzamento')),
                ('conduttore', models.TextField()),
                ('proprietario', models.TextField()),
                ('localita', models.TextField(verbose_name='Localit\xe0')),
                ('cap_di_campo', models.FloatField(help_text='celle C16', verbose_name='capacit\xe0 di campo')),
                ('punto_appassimento', models.FloatField(help_text='celle C17', verbose_name='punto di appassimento')),
                ('perc_sabbia', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='percentuale sabbia')),
                ('perc_argilla', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='percentuale argilla')),
                ('perc_limo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='percentuale limo')),
                ('den_app', models.FloatField(verbose_name='densit\xe0 apparente del terreno')),
                ('cap_idrica', models.FloatField(help_text='celle C18 e C3', verbose_name='capacit\xe0 idrica massima')),
                ('ris_fac_util', models.FloatField(help_text='celle C4', verbose_name='riserva facilmente utilizzabile')),
                ('vol_irriguo', models.FloatField(verbose_name='dose intervento irriguo')),
                ('perc_riserva_util', models.PositiveIntegerField(help_text='celle C5', verbose_name='percentuale riserva facilmente utilizzabile')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Appezzamento',
                'verbose_name_plural': 'Appezzamenti',
            },
        ),
        migrations.CreateModel(
            name='bilancio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rif', models.DateField(default=dateutil.utils.today, verbose_name='data calcolo bilancio')),
                ('pioggia_cum', models.FloatField(default=0.0, verbose_name='pioggia cumulata')),
                ('Kc', models.FloatField(default=0.0)),
                ('Et0', models.FloatField(default=0.0, verbose_name='EvapoTraspirazione metodo esteso')),
                ('Etc', models.FloatField(default=0.0)),
                ('P_ep', models.FloatField(default=0.0, verbose_name='P - Ep (mm)')),
                ('L', models.FloatField(default=0.0)),
                ('Lambda', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('Au', models.FloatField(default=0.0, verbose_name='A>U mm')),
                ('A', models.FloatField(default=0.0, help_text='colonna L', verbose_name='capacit\xe0 idrica massima')),
                ('Irrigazione', models.NullBooleanField(default=False)),
                ('dose', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('Irr_mm', models.FloatField(default=0.0, verbose_name='Irrigazione in mm')),
                ('appezzamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consiglio.appezzamento')),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.stazioni_retevista')),
            ],
            options={
                'ordering': ('-data_rif',),
                'verbose_name': 'Bilancio',
                'verbose_name_plural': 'Bilanci',
            },
        ),
        migrations.CreateModel(
            name='coltura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.TextField()),
                ('data_semina', models.DateField(verbose_name='data di semina o trapianto')),
                ('durata_ciclo', models.PositiveIntegerField(verbose_name='durata ciclo colturale')),
                ('strato_radici', models.FloatField(verbose_name='strato esplorato dalle radici')),
                ('kc_ini', models.FloatField(verbose_name='Kc ini')),
                ('kc_med', models.FloatField(verbose_name='Kc med')),
                ('kc_end', models.FloatField(verbose_name='Kc end')),
                ('durata_kc_ini', models.FloatField(verbose_name='durata giorni kc ini')),
                ('durata_kc_dev', models.FloatField(default=1.0, verbose_name='durata giorni kc dev')),
                ('durata_kc_med', models.FloatField(verbose_name='durata giorni kc med')),
                ('durata_kc_end', models.FloatField(verbose_name='durata giorni kc end')),
            ],
            options={
                'verbose_name': 'Coltura',
                'verbose_name_plural': 'Colture',
            },
        ),
        migrations.CreateModel(
            name='settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('metodo', models.TextField(verbose_name='metodo irriguo')),
                ('data', models.DateField(verbose_name='data ultimo apporto irriguo')),
                ('volume', models.PositiveIntegerField(verbose_name="volume dell'ultimo apporto irriguo")),
            ],
            options={
                'verbose_name_plural': 'Settori',
            },
        ),
        migrations.AddField(
            model_name='appezzamento',
            name='coltura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consiglio.coltura'),
        ),
        migrations.AddField(
            model_name='appezzamento',
            name='settore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consiglio.settore'),
        ),
    ]
