# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 12:37
from __future__ import unicode_literals

import dateutil.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        ('consiglio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bilancio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rif', models.DateField(default=dateutil.utils.today, verbose_name='data calcolo bilancio')),
                ('pioggia_cum', models.FloatField(default=0.0, verbose_name='pioggia cumulata')),
                ('Kc', models.FloatField(default=0.0)),
                ('Et0', models.FloatField(default=0.0, verbose_name='EvapoTraspirazione metodo esteso')),
                ('Etc', models.FloatField(default=0.0)),
                ('P_ep', models.FloatField(default=0.0, verbose_name='P - Ep (mm)')),
                ('L', models.FloatField(default=0.0)),
                ('Lambda', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('Au', models.FloatField(default=0.0, verbose_name='A>U mm')),
                ('A', models.FloatField(default=0.0, help_text='colonna L', verbose_name='capacit\xe0 idrica massima')),
                ('Irrigazione', models.NullBooleanField(default=False)),
                ('dose', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('Irr_mm', models.FloatField(default=0.0, verbose_name='Irrigazione in mm')),
                ('appezzamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consiglio.appezzamento')),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.stazioni_retevista')),
            ],
            options={
                'ordering': ('-data_rif',),
                'verbose_name': 'Bilancio',
                'verbose_name_plural': 'Bilanci',
            },
        ),
    ]
