# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dati_aggregati_daily',
            options={'ordering': ('-data',)},
        ),
        migrations.AddField(
            model_name='dati_orari',
            name='et_cum_year',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Et cum grezza'),
        ),
        migrations.AddField(
            model_name='dati_orari',
            name='rain_cum_year',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rain cum grezza'),
        ),
        migrations.AlterField(
            model_name='dati_aggregati_daily',
            name='rain_cumulata',
            field=models.FloatField(blank=True, help_text='pioggia cumulata giornaliera', null=True, verbose_name='pioggia cum. giornaliera'),
        ),
    ]
