# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20190220_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dati_orari',
            name='et_cum_day',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Et cum giornaliera'),
        ),
        migrations.AddField(
            model_name='dati_orari',
            name='et_cum_month',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Et cum mensile'),
        ),
        migrations.AddField(
            model_name='dati_orari',
            name='rain_cum_day',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rain cum giornaliera'),
        ),
        migrations.AddField(
            model_name='dati_orari',
            name='rain_cum_month',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rain cum mensile'),
        ),
        migrations.AlterField(
            model_name='dati_aggregati_daily',
            name='wind_speed_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocit\xe0 vento media'),
        ),
        migrations.AlterField(
            model_name='dati_orari',
            name='et_cum_year',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Et cum annuale'),
        ),
        migrations.AlterField(
            model_name='dati_orari',
            name='rain_cum_year',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rain cum annuale'),
        ),
    ]
