# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20190225_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dati_aggregati_daily',
            name='note',
            field=models.CharField(default='', max_length=2500, verbose_name='Note'),
        ),
    ]
